# Generated by Django 3.1.6 on 2021-06-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_Gallery', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
